steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/laurent-pipeline/node_resume", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/laurent-pipeline/node_resume"]   
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - run
      - deploy
      - node-resume
      - --image=gcr.io/laurent-pipeline/node_resume:latest
      - --memory=1Gi
      - --cpu=1
      - --concurrency=100
      - --platform=managed
      - --region=northamerica-northeast1
      - --allow-unauthenticated
      - --port=8080
timeout: 900s 