steps:
# Install dependencies
- name: node
  entrypoint: npm
  args: ['install']
# Run tests
- name: node
  entrypoint: npm
  args: ['test']
- name: node
  entrypoint: npm
    args:
      - run
      - deploy
      - node-resume
      - --image=gcr.io/laurent-pipeline/node_resume:latest
      - --memory=1Gi
      - --cpu=1
      - --concurrency=100
      - --platform=managed
      - --region=northamerica-northeast1
      - --allow-unauthenticated
      - --port=8080
timeout: 900s 